### ISSUE TITLE
处理完一个非跳过文件夹, 稳定触发TypeError: 'NoneType' object is not iterable 报错

### ISSUE THREAD

**Issue by ironstress** [xjxjin/alist-sync#10]
**环境**
   青龙:正式版 v2.17.11
   脚本:gitee最新
   alist:v3.37.2
   SYNC_DELETE_ACTION: delete(或者是move)
**任务**: 天翼云向和彩云同步, 创建一个文件夹, 添加本文件夹的复制任务, 就会报错. 每次跑脚本只会处理一个文件夹.

> Traceback (most recent call last):
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 307, in <module>
    main()  # 执行一次同步任务
    ^^^^^^
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 293, in main
    recursive_copy(src_dir, dst_dir, conn, token, sync_delete)
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 198, in recursive_copy
    recursive_copy(item_path, dst_item_path, connection, token, sync_delete)
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 198, in recursive_copy
    recursive_copy(item_path, dst_item_path, connection, token, sync_delete)
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 214, in recursive_copy
    for dst_item in dst_contents:
TypeError: 'NoneType' object is not iterable

**Comment by ironstress** [comment]
根据报错提示, 我将SYNC_DELETE_ACTION改为none则可以正常执行
