### ISSUE TITLE
遍历到最后一个目录的时候报错

### ISSUE THREAD

**Issue by qq1090605939** [xjxjin/alist-sync#11]
Traceback (most recent call last):
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 307, in <module>
    main()  # 执行一次同步任务
    ^^^^^^
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 293, in main
    recursive_copy(src_dir, dst_dir, conn, token, sync_delete)
  File "/ql/data/scripts/raw_main_alist-sync-ql.py", line 214, in recursive_copy
    for dst_item in dst_contents:
TypeError: 'NoneType' object is not iterable

遍历到最后一个目录的时候报错，此处应该要加个判空吧

多个目录要同步的时候，有一个目录执行报错，整个脚本都停止了，建议捕捉一下异常，让其他目录能继续同步

**Comment by xjxjin** [comment]
已经修复
